#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────
# Deploy memory-service to Fly.io (free tier)
#
# Prerequisites:
#   - flyctl installed (https://fly.io/docs/flyctl/install/)
#   - Authenticated: fly auth login
#
# Usage:
#   ./deploy/fly/deploy.sh              # first-time setup + deploy
#   ./deploy/fly/deploy.sh deploy-only  # redeploy (skip infra setup)
# ─────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"
umask 077

APP_NAME="${FLY_APP_NAME:-memory-service-poc}"
PG_APP_NAME="${APP_NAME}-db"
REGION="${FLY_REGION:-lhr}"
GENERATED_SECRETS_FILE="${FLY_GENERATED_SECRETS_FILE:-deploy/fly/.env}"

# ── Colors ──────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[+]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
error() { echo -e "${RED}[x]${NC} $*" >&2; }

# ── Preflight checks ───────────────────────────────────────
if ! command -v fly &>/dev/null; then
    error "flyctl not found. Install it: https://fly.io/docs/flyctl/install/"
    exit 1
fi

if ! fly auth whoami &>/dev/null; then
    error "Not authenticated. Run: fly auth login"
    exit 1
fi

info "Authenticated as: $(fly auth whoami)"

# ── Deploy-only mode (skip infra creation) ──────────────────
if [ "${1:-}" = "deploy-only" ]; then
    info "Deploying $APP_NAME (skip infra setup)..."
    fly deploy --config ./deploy/fly/fly.toml --app "$APP_NAME"
    info "Deployed! URL: https://${APP_NAME}.fly.dev"
    exit 0
fi

# ── Step 1: Create the Fly app ──────────────────────────────
if fly apps list | grep -q "^$APP_NAME "; then
    info "App '$APP_NAME' already exists, skipping creation."
else
    info "Creating app '$APP_NAME' in region '$REGION'..."
    fly apps create "$APP_NAME" --machines
fi

# ── Step 4: Generate and set secrets ────────────────────────
info "Setting secrets..."

SECRETS=()
GENERATED_SECRETS=()

add_secret() {
    local key="$1"
    local value="$2"

    if [[ ! "$key" =~ ^MEMORY_SERVICE_[A-Z0-9_]+$ ]]; then
        error "Invalid memory-service secret name: $key"
        exit 1
    fi
    if [ -z "$value" ]; then
        error "Secret $key must not be empty"
        exit 1
    fi

    SECRETS+=("$key=$value")
}

record_generated_secret() {
    GENERATED_SECRETS+=("$1=$2")
}

if [ -z "${MEMORY_SERVICE_API_KEYS_AGENT+x}" ]; then
    MEMORY_SERVICE_API_KEYS_AGENT="$(openssl rand -hex 24)"
    record_generated_secret "MEMORY_SERVICE_API_KEYS_AGENT" "$MEMORY_SERVICE_API_KEYS_AGENT"
fi
add_secret "MEMORY_SERVICE_API_KEYS_AGENT" "$MEMORY_SERVICE_API_KEYS_AGENT"

if [ -z "${MEMORY_SERVICE_ENCRYPTION_DEK_KEY+x}" ]; then
    MEMORY_SERVICE_ENCRYPTION_DEK_KEY="$(openssl rand -hex 32)"
    record_generated_secret "MEMORY_SERVICE_ENCRYPTION_DEK_KEY" "$MEMORY_SERVICE_ENCRYPTION_DEK_KEY"
fi
add_secret "MEMORY_SERVICE_ENCRYPTION_DEK_KEY" "$MEMORY_SERVICE_ENCRYPTION_DEK_KEY"

EXTRA_SECRET_NAMES="${FLY_MEMORY_SERVICE_SECRET_NAMES:-}"
EXTRA_SECRET_NAMES="${EXTRA_SECRET_NAMES//,/ }"
for secret_name in $EXTRA_SECRET_NAMES; do
    if [[ ! "$secret_name" =~ ^MEMORY_SERVICE_[A-Z0-9_]+$ ]]; then
        error "Invalid name in FLY_MEMORY_SERVICE_SECRET_NAMES: $secret_name"
        exit 1
    fi
    if [ -z "${!secret_name+x}" ]; then
        error "FLY_MEMORY_SERVICE_SECRET_NAMES includes $secret_name but it is not set"
        exit 1
    fi
    add_secret "$secret_name" "${!secret_name}"
done

if [ "${#GENERATED_SECRETS[@]}" -gt 0 ]; then
    mkdir -p "$(dirname "$GENERATED_SECRETS_FILE")"
    {
        echo "# Generated by deploy/fly/deploy.sh. Store securely; do not commit."
        printf '%s\n' "${GENERATED_SECRETS[@]}"
    } > "$GENERATED_SECRETS_FILE"
    chmod 600 "$GENERATED_SECRETS_FILE"
    info "Generated secrets saved to $GENERATED_SECRETS_FILE with mode 0600."
fi

printf '%s\n' "${SECRETS[@]}" | fly secrets import --app "$APP_NAME"

info "Secrets set."
echo ""
warn "Generated secret values are not printed. If this run generated values, save $GENERATED_SECRETS_FILE securely."
echo ""

# # ── Step 5: Deploy ──────────────────────────────────────────
info "Deploying $APP_NAME..."
fly deploy --app "$APP_NAME" --config ./deploy/fly/fly.toml

echo ""
info "Deployment complete!"
echo ""
echo "  URL:     https://${APP_NAME}.fly.dev"
echo "  API Key: use the value you provided or the generated value in $GENERATED_SECRETS_FILE"
echo ""
echo "  Test it:"
echo "    curl -s https://${APP_NAME}.fly.dev/ready"
echo "    curl -s -H 'Authorization: Bearer <API_KEY>' \\"
echo "      https://${APP_NAME}.fly.dev/v1/conversations | jq ."
echo ""
echo "  Redeploy after code changes:"
echo "    ./deploy/fly/deploy.sh deploy-only"
echo ""
echo "  Logs:"
echo "    fly logs --app $APP_NAME"
echo ""
echo "  Postgres console:"
echo "    fly postgres connect --app $PG_APP_NAME"
