-- Liquibase-managed PostgreSQL schema for Memory Service
-- Copied from the top-level schema.sql specification.

-- PostgreSQL schema for Memory Service
-- UUID values are generated by the application; the database does not rely
-- on the uuid-ossp extension. If pgvector is used, enable it separately
-- where appropriate (e.g., via migrations or deployment scripts).
-- Example (optional): CREATE EXTENSION IF NOT EXISTS vector;

-- Conversations & ownership
-------------------------------------------------------------

CREATE TABLE IF NOT EXISTS conversation_groups (
    id              UUID PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS conversations (
    id              UUID PRIMARY KEY,
    title           BYTEA,
    -- External user identifier (e.g., OAuth subject); no local users table.
    owner_user_id   TEXT NOT NULL,
    metadata        JSONB NOT NULL DEFAULT '{}'::JSONB,
    conversation_group_id UUID NOT NULL REFERENCES conversation_groups (id) ON DELETE CASCADE,
    forked_at_message_id UUID,
    forked_at_conversation_id UUID REFERENCES conversations (id) ON DELETE CASCADE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    vectorized_at   TIMESTAMPTZ
);

-- Per-user access to conversations.
-- Exactly one row per conversation with access_level = 'owner'.
CREATE TABLE IF NOT EXISTS conversation_memberships (
    conversation_group_id   UUID NOT NULL REFERENCES conversation_groups (id) ON DELETE CASCADE,
    -- External user identifier (e.g., OAuth subject); no local users table.
    user_id           TEXT NOT NULL,
    access_level      TEXT NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (conversation_group_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_conversation_memberships_user
    ON conversation_memberships (user_id, conversation_group_id);

------------------------------------------------------------
-- Messages & summaries
------------------------------------------------------------

CREATE TABLE IF NOT EXISTS messages (
    id                UUID PRIMARY KEY,
    conversation_id   UUID NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
    conversation_group_id UUID NOT NULL REFERENCES conversation_groups (id) ON DELETE CASCADE,
    user_id           TEXT,
    client_id         TEXT,
    channel           TEXT NOT NULL,
    memory_epoch      BIGINT,
    content           BYTEA NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_created_at
    ON messages (conversation_id, created_at);

CREATE INDEX IF NOT EXISTS idx_messages_group_created_at
    ON messages (conversation_group_id, created_at);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_channel_client_epoch_created_at
    ON messages (conversation_id, channel, client_id, memory_epoch, created_at);

CREATE INDEX IF NOT EXISTS idx_conversations_group
    ON conversations (conversation_group_id);

CREATE INDEX IF NOT EXISTS idx_conversations_forked_at_conversation
    ON conversations (forked_at_conversation_id);

CREATE INDEX IF NOT EXISTS idx_conversations_forked_at_message
    ON conversations (forked_at_message_id);

------------------------------------------------------------
-- Semantic search (pgvector-backed, optional)
------------------------------------------------------------

-- If pgvector is enabled, uncomment the extension above and this table.
-- Embeddings are associated with individual messages.
-- CREATE TABLE IF NOT EXISTS message_embeddings (
--     message_id       UUID PRIMARY KEY REFERENCES messages (id) ON DELETE CASCADE,
--     conversation_id  UUID NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
--     -- Adjust dimension to match the configured embedding model.
--     embedding        vector(768) NOT NULL,
--     created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );
--
-- CREATE INDEX IF NOT EXISTS idx_message_embeddings_conversation
--     ON message_embeddings (conversation_id);
--
-- CREATE INDEX IF NOT EXISTS idx_message_embeddings_embedding
--     ON message_embeddings
--     USING ivfflat (embedding vector_cosine_ops)
--     WITH (lists = 100);

------------------------------------------------------------
-- Ownership transfer tracking
------------------------------------------------------------

CREATE TABLE IF NOT EXISTS conversation_ownership_transfers (
    id                UUID PRIMARY KEY,
    conversation_group_id   UUID NOT NULL REFERENCES conversation_groups (id) ON DELETE CASCADE,
    -- External user identifiers (e.g., OAuth subjects).
    from_user_id      TEXT NOT NULL,
    to_user_id        TEXT NOT NULL,
    status            TEXT NOT NULL DEFAULT 'pending',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ownership_transfers_to_user
    ON conversation_ownership_transfers (to_user_id, status);
