// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type ErrorResponse = {
  /**
   * Stable machine-readable error code.
   */
  code: string;
  /**
   * Safe human-readable error message.
   */
  error: string;
  /**
   * Request correlation identifier, also returned in the X-Request-ID header.
   */
  requestId: string;
  /**
   * Structured non-sensitive error details.
   */
  details?: {
    [key: string]: unknown;
  };
};

/**
 * Error response when the requested search type is not available on the server.
 */
export type SearchTypeUnavailableError = {
  /**
   * Stable machine-readable error code.
   */
  code: string;
  /**
   * Safe human-readable error message.
   */
  error: string;
  /**
   * Request correlation identifier, also returned in the X-Request-ID header.
   */
  requestId: string;
  /**
   * Structured non-sensitive error details, including availableTypes when known.
   */
  details?: {
    [key: string]: unknown;
  };
};

export type CapabilitiesResponse = {
  version: string;
  tech: CapabilitiesTech;
  features: CapabilitiesFeatures;
  auth: CapabilitiesAuth;
  security: CapabilitiesSecurity;
};

export type CapabilitiesTech = {
  store: string;
  attachments: string;
  cache: string;
  vector: string;
  event_bus: string;
  embedder: string;
};

export type CapabilitiesFeatures = {
  outbox_enabled: boolean;
  semantic_search_enabled: boolean;
  fulltext_search_enabled: boolean;
  cors_enabled: boolean;
  management_listener_enabled: boolean;
  private_source_urls_enabled: boolean;
  s3_direct_download_enabled: boolean;
};

export type CapabilitiesAuth = {
  oidc_enabled: boolean;
  api_key_enabled: boolean;
  admin_justification_required: boolean;
  user_id_assertion_enabled: boolean;
};

export type CapabilitiesSecurity = {
  encryption_enabled: boolean;
  db_encryption_enabled: boolean;
  attachment_encryption_enabled: boolean;
};

/**
 * Access level of a user for a conversation.
 */
export type AccessLevel = "owner" | "manager" | "writer" | "reader";

export type ConversationSummary = {
  /**
   * Unique identifier for the conversation.
   */
  id?: string;
  title?: string;
  ownerUserId?: string;
  createdAt?: string;
  updatedAt?: string;
  lastMessagePreview?: string;
  accessLevel?: AccessLevel;
  startedByConversationId?: string;
  startedByEntryId?: string;
  /**
   * Synthetic archive flag derived from the internal archived timestamp.
   */
  archived?: boolean;
};

export type ChildConversationSummary = {
  /**
   * Unique identifier for the child conversation.
   */
  id?: string;
  title?: string;
  ownerUserId?: string;
  createdAt?: string;
  updatedAt?: string;
  lastMessagePreview?: string;
  accessLevel?: AccessLevel;
  startedByEntryId?: string;
  /**
   * Synthetic archive flag derived from the internal archived timestamp.
   */
  archived?: boolean;
};

export type Conversation = ConversationSummary & {
  /**
   * Optional logical agent associated with this conversation.
   */
  agentId?: string;
  /**
   * First parent entry excluded by this fork. Valid fork anchors are history entries and journal entries visible to the same authenticated client; context entries cannot be fork anchors. Null for root conversations and blank-slate forks that inherit no parent entries.
   */
  forkedAtEntryId?: string;
  /**
   * Conversation ID from which this conversation was forked.
   */
  forkedAtConversationId?: string;
  /**
   * Parent conversation that started this child conversation.
   */
  startedByConversationId?: string;
  /**
   * Parent entry that started this child conversation.
   */
  startedByEntryId?: string;
};

export type CreateConversationRequest = {
  /**
   * Optional client-supplied conversation ID. When provided, the server creates the conversation with exactly this ID instead of generating one. Useful for agents that need a deterministic conversation ID derived from an external thread identifier.
   */
  id?: string;
  title?: string;
  /**
   * Optional logical agent to associate with the new conversation.
   */
  agentId?: string;
  metadata?: {
    [key: string]: unknown;
  };
};

export type UpdateConversationRequest = {
  title?: string;
  /**
   * Set to `true` to archive the conversation and its fork tree.
   */
  archived?: boolean;
};

export type ConversationMembership = {
  /**
   * Unique identifier for the conversation.
   */
  conversationId?: string;
  userId?: string;
  accessLevel?: AccessLevel;
  createdAt?: string;
};

/**
 * Summary of a forked conversation originating at a given entry.
 */
export type ConversationForkSummary = {
  /**
   * Unique identifier for the forked conversation.
   */
  conversationId?: string;
  /**
   * First parent entry excluded by this fork. Valid fork anchors are history entries and journal entries visible to the same authenticated client; context entries cannot be fork anchors. Null for blank-slate forks that inherit no parent entries.
   */
  forkedAtEntryId?: string;
  /**
   * Conversation ID where the fork occurred.
   */
  forkedAtConversationId?: string;
  title?: string;
  createdAt?: string;
};

export type ConversationForkNavigation = {
  conversationIds: Array<string>;
  forkPoints: Array<ConversationForkPoint>;
};

export type ConversationForkPoint = {
  /**
   * Visible entry in the requested conversation where the fork selector is rendered.
   */
  entryId: string;
  options: Array<ConversationForkOption>;
};

export type ConversationForkOption = {
  conversationId: string;
  /**
   * Equivalent display entry for this continuation; null for an empty fork.
   */
  entryId?: string;
  title: string;
  preview?: string;
  createdAt: string;
};

export type ShareConversationRequest = {
  userId: string;
  accessLevel: AccessLevel;
  createdAt?: string;
};

/**
 * Logical channel of the entry within the conversation.
 */
export type Channel = "history" | "context" | "journal";

export type PutMemoryRequest = {
  namespace: Array<string>;
  key: string;
  value: {
    [key: string]: unknown;
  };
  ttl_seconds?: number;
  index?: {
    [key: string]: string;
  };
  /**
   * Optional optimistic concurrency revision expected for the active memory.
   */
  expected_revision?: number;
};

export type MemoryWriteResult = {
  id?: string;
  namespace?: Array<string>;
  key?: string;
  attributes?: {
    [key: string]: unknown;
  };
  createdAt?: string;
  expiresAt?: string;
  revision?: number;
};

export type MemorySearchQuery = {
  /**
   * The search string for this query. Must be non-empty.
   */
  text: string;
  /**
   * Human-readable label used as attribution in matchedQueries. Defaults to text when absent.
   */
  purpose?: string;
};

export type MemoryItem = {
  id?: string;
  namespace?: Array<string>;
  key?: string;
  value?: {
    [key: string]: unknown;
  };
  attributes?: {
    [key: string]: unknown;
  };
  score?: number;
  /**
   * Attribution — purposes (or texts) of all queries that matched this item. Present only in multi-query responses.
   */
  matchedQueries?: Array<string>;
  createdAt?: string;
  expiresAt?: string;
  usage?: MemoryUsage;
  /**
   * Synthetic archive flag derived from the internal archived timestamp.
   */
  archived?: boolean;
};

export type UpdateMemoryRequest = {
  /**
   * Set to `true` to archive the active memory item.
   */
  archived?: boolean;
  /**
   * Optional optimistic concurrency revision expected for the active memory.
   */
  expected_revision?: number;
};

export type MemoryUsage = {
  fetchCount?: number;
  lastFetchedAt?: string;
};

export type SearchMemoriesRequest = {
  namespace_prefix: Array<string>;
  /**
   * Single semantic search string. Mutually exclusive with queries.
   */
  query?: string;
  /**
   * Batch of semantic search strings for multi-query retrieval. Mutually exclusive with query.
   */
  queries?: Array<MemorySearchQuery>;
  /**
   * Per-query vector search budget. Defaults to limit when absent.
   */
  per_query_limit?: number;
  filter?: {
    [key: string]: unknown;
  };
  /**
   * Maximum number of results to return. The server may enforce a lower configured maximum.
   */
  limit?: number;
  include_usage?: boolean;
  archived?: "exclude" | "include" | "only";
};

export type SearchMemoriesResponse = {
  items?: Array<MemoryItem>;
};

export type ListMemoryNamespacesResponse = {
  namespaces?: Array<Array<string>>;
};

export type MemoryEventItem = {
  id?: string;
  namespace?: Array<string>;
  key?: string;
  kind?: "add" | "update" | "expired";
  occurred_at?: string;
  value?: {
    [key: string]: unknown;
  };
  attributes?: {
    [key: string]: unknown;
  };
  expires_at?: string;
};

export type ListMemoryEventsResponse = {
  events?: Array<MemoryEventItem>;
  after_cursor?: string;
};

/**
 * A reference to an attachment on a history entry. Supports two modes:
 *
 * **External URL (Phase 1)**: Provide `href` and `contentType` to reference
 * an externally-hosted resource.
 *
 * **Server-stored (Phase 2)**: Provide `attachmentId` to reference a file
 * previously uploaded via `POST /v1/attachments`. When the entry is created,
 * the server preserves `attachmentId` and links the attachment to the entry.
 *
 * At least one of `href` or `attachmentId` must be present.
 */
export type Attachment = {
  /**
   * URL to the attachment resource (external or server-relative).
   */
  href?: string;
  /**
   * ID of a previously uploaded attachment (from POST /v1/attachments).
   * When the entry is created, this is preserved as the stable server-stored
   * attachment reference.
   */
  attachmentId?: string;
  /**
   * MIME type of the attachment (e.g., "image/jpeg", "audio/mp3"). Required when href is provided directly.
   */
  contentType?: string;
  /**
   * Optional display name for the attachment.
   */
  name?: string;
  /**
   * Optional alt text or description.
   */
  description?: string;
  /**
   * File size in bytes (set by server for uploaded attachments).
   */
  size?: number;
  /**
   * SHA-256 hash of the file content (set by server for uploaded attachments).
   */
  sha256?: string;
};

/**
 * Request to create an attachment from a source URL.
 */
export type CreateFromUrlRequest = {
  /**
   * URL of the content to download and store as an attachment.
   */
  sourceUrl: string;
  /**
   * MIME type of the content. Defaults to application/octet-stream.
   */
  contentType?: string;
  /**
   * Display name for the attachment.
   */
  name?: string;
};

/**
 * Response from uploading or creating an attachment.
 */
export type AttachmentUploadResponse = {
  /**
   * Unique identifier for the uploaded attachment.
   */
  id?: string;
  /**
   * Server-relative URL to retrieve the attachment.
   */
  href?: string;
  /**
   * MIME type of the uploaded file.
   */
  contentType?: string;
  /**
   * Original filename of the uploaded file.
   */
  filename?: string;
  /**
   * File size in bytes (null for URL-created attachments until download completes).
   */
  size?: number;
  /**
   * SHA-256 hash of the file content (null for URL-created attachments until download completes).
   */
  sha256?: string;
  /**
   * When this unlinked attachment will expire and be deleted.
   */
  expiresAt?: string;
  /**
   * Current status of the attachment:
   * - `uploading` - Multipart upload created but not yet completed
   * - `downloading` - Server is downloading content from sourceUrl
   * - `ready` - Content is available for retrieval
   * - `failed` - Download from sourceUrl failed
   */
  status?: "uploading" | "downloading" | "ready" | "failed";
  /**
   * Original source URL (only present for URL-created attachments).
   */
  sourceUrl?: string;
};

/**
 * Response containing a signed download URL for an attachment.
 */
export type AttachmentDownloadUrlResponse = {
  /**
   * The signed download URL. May be an absolute S3 URL or a server-relative path.
   */
  url?: string;
  /**
   * Number of seconds until the URL expires.
   */
  expiresIn?: number;
};

export type Entry = {
  /**
   * Unique identifier for the entry.
   */
  id: string;
  /**
   * Unique identifier for the conversation this entry belongs to.
   */
  conversationId: string;
  /**
   * Human user this entry is associated with.
   * For history entries authored by a user, this is the sender.
   * For agent entries, this is the user the agent is responding to.
   */
  userId?: string;
  channel: Channel;
  /**
   * Logical context epoch this entry belongs to.
   * For history entries this is typically null. For context entries,
   * the agent increments the epoch when starting a new context version.
   */
  epoch?: number;
  /**
   * Describes the schema/format of the content array.
   *
   * **History channel entries must use `"history"` or `"history/<subtype>"` as the contentType.**
   *
   * Supported content types:
   * - `history` - Simple text-only history entries
   * - `history/lc4j` - LangChain4j rich event format (Quarkus)
   *
   * The content array for history entries contains objects with:
   * - `role` (string, required): Either `"USER"` or `"AI"`.
   * - `text` (string, optional): The message text. At least one of `text`, `events`, or `attachments` must be present.
   * - `events` (array, optional): Rich event objects for streaming details.
   * Event structure is not validated by the server. For `history/lc4j`, events use an `eventType` field:
   * - `PartialResponse`: Text chunk (`{eventType, chunk}`)
   * - `PartialThinking`: Reasoning chunk (`{eventType, chunk}`)
   * - `BeforeToolExecution`: Before tool call (`{eventType, toolName, input}`)
   * - `ToolExecuted`: Tool result (`{eventType, toolName, output}`)
   * - `attachments` (array, optional): Array of `Attachment` objects referencing external resources (images, audio, video, documents).
   *
   * Other contentTypes (e.g., `"LC4J"`, `"SpringAI"`) may be used for
   * agent context entries.
   */
  contentType: string;
  /**
   * Opaque, agent-defined content blocks.
   * Different agents may use different schemas; the memory-service
   * stores and returns them without interpretation.
   *
   * For history channel entries (contentType: `"history"`), each block
   * contains `role` and at least one of `text`, `events`, or `attachments`.
   */
  content: Array<unknown>;
  /**
   * Optional client-assigned sequence number, unique within the conversation.
   * Default listing uses seq only as a createdAt tie-breaker, with entries
   * without seq sorted before sequenced entries at the same timestamp. Gaps
   * are permitted.
   */
  seq?: number;
  createdAt: string;
};

export type CreateEntryRequest = {
  /**
   * Human user this entry is associated with.
   * For history entries authored by a user, this is the sender.
   * For agent entries, this is the user the agent is responding to.
   */
  userId?: string;
  /**
   * Optional logical agent to associate with the conversation when this request auto-creates a new conversation. Ignored for existing conversations.
   */
  agentId?: string;
  channel?: Channel;
  /**
   * Describes the schema/format of the content array.
   *
   * **History channel entries must use `"history"` or `"history/<subtype>"` as the contentType.**
   *
   * Supported content types:
   * - `history` - Simple text-only history entries
   * - `history/lc4j` - LangChain4j rich event format (Quarkus)
   *
   * The content array for history entries must contain exactly 1 object with:
   * - `role` (string, required): Either `"USER"` or `"AI"`.
   * - `text` (string, optional): The message text. At least one of `text`, `events`, or `attachments` must be present.
   * - `events` (array, optional): Rich event objects for streaming details.
   * Event structure is not validated by the server. For `history/lc4j`, events use an `eventType` field:
   * - `PartialResponse`: Text chunk (`{eventType, chunk}`)
   * - `PartialThinking`: Reasoning chunk (`{eventType, chunk}`)
   * - `BeforeToolExecution`: Before tool call (`{eventType, toolName, input}`)
   * - `ToolExecuted`: Tool result (`{eventType, toolName, output}`)
   * - `attachments` (array, optional): Array of `Attachment` objects referencing external resources (images, audio, video, documents).
   *
   * Other contentTypes (e.g., `"LC4J"`, `"SpringAI"`) may be used for
   * agent context entries.
   */
  contentType: string;
  /**
   * For history channel entries (contentType: `"history"` or `"history/<subtype>"`), each block
   * contains `role` and at least one of `text`, `events`, or `attachments`.
   */
  content: Array<unknown>;
  /**
   * Optional text to index for search. Only valid for entries in the history
   * channel. If provided, the entry will be indexed for search immediately
   * after creation. Returns 400 Bad Request if specified for non-history channels.
   */
  indexedContent?: string;
  /**
   * If the target conversation doesn't exist yet, auto-create it as a fork of this conversation. Ignored when the conversation already exists.
   */
  forkedAtConversationId?: string;
  /**
   * Entry ID marking the fork point. Entries before this point are inherited; entries at and after this point are excluded. Valid fork anchors are history entries and journal entries visible to the same authenticated client; context entries cannot be fork anchors. Optional; when unset, all entries are excluded. New messages added will show up as the first message of the fork.
   */
  forkedAtEntryId?: string;
  /**
   * If the target conversation does not exist yet, auto-create it as a child conversation started from this parent conversation.
   */
  startedByConversationId?: string;
  /**
   * Optional parent entry that caused this child conversation to be started.
   */
  startedByEntryId?: string;
  /**
   * Optional client-assigned sequence number. Must be unique within the
   * conversation. Must be >= 0. Returns 409 Conflict if a duplicate seq is
   * submitted. Returns 400 Bad Request if the value is negative or exceeds
   * 4294967295.
   */
  seq?: number;
};

export type SyncEntryResponse = {
  /**
   * The epoch number that now reflects the stored context state.
   */
  epoch?: number;
  /**
   * True when the request resulted in no stored changes.
   */
  noOp?: boolean;
  /**
   * True when the provided list diverged and a new epoch was started.
   */
  epochIncremented?: boolean;
  /**
   * The entry that was appended during this sync, or null if no-op.
   */
  entry?: Entry;
};

export type IndexEntryRequest = {
  /**
   * The conversation containing the entry.
   */
  conversationId: string;
  /**
   * The entry ID to index.
   */
  entryId: string;
  /**
   * The searchable text for this entry.
   */
  indexedContent: string;
};

export type IndexConversationsResponse = {
  /**
   * Number of entries processed. These entries have their indexed content
   * stored and will be searchable. If vector store indexing failed for some
   * entries, they will become searchable asynchronously via background retry.
   */
  indexed?: number;
};

export type UnindexedEntriesResponse = {
  data?: Array<UnindexedEntry>;
  /**
   * Cursor for fetching next page. Null when no more results.
   */
  afterCursor?: string;
};

export type UnindexedEntry = {
  conversationId?: string;
  entry?: Entry;
};

export type SearchConversationsSearchTypeSingle = "auto" | "semantic" | "fulltext";

export type SearchConversationsSearchTypeList = Array<"semantic" | "fulltext">;

export type SearchConversationsRequest = {
  /**
   * Natural language query.
   */
  query: string;
  /**
   * The search method(s) to use:
   * - `auto` (default): Try semantic (vector) search first, fall back to full-text if no results or unavailable
   * - `semantic`: Use only vector/embedding-based semantic search
   * - `fulltext`: Use only PostgreSQL full-text search with GIN index
   *
   * `searchType` may be provided as either a single string or an array of concrete types.
   * When an array is provided (for example `["semantic","fulltext"]`), each type executes
   * independently and `limit` is applied per type. The combined response may therefore contain
   * up to `limit * number_of_requested_types` entries.
   *
   * If the requested search type is not available on the server, a 501 (Not Implemented)
   * error is returned with details about which search types are available.
   *
   */
  searchType?: SearchConversationsSearchTypeSingle | SearchConversationsSearchTypeList;
  /**
   * Cursor for pagination; returns items after this result.
   */
  afterCursor?: string;
  /**
   * Maximum number of results to return. The server may enforce a lower configured maximum.
   */
  limit?: number;
  /**
   * Whether to include the full entry in results. Set to false to reduce response size when only metadata is needed.
   */
  includeEntry?: boolean;
  /**
   * When true (default), groups results by conversation and returns only
   * the highest-scoring entry per conversation. When false, returns all
   * matching entries ordered by score.
   *
   */
  groupByConversation?: boolean;
};

export type SearchResult = {
  /**
   * Unique identifier of the conversation containing this entry.
   */
  conversationId?: string;
  /**
   * Title of the conversation containing this entry.
   */
  conversationTitle?: string;
  /**
   * ID of the matched entry. Always present for deep-linking.
   */
  entryId?: string;
  /**
   * Relevance score. Higher is more relevant.
   */
  score?: number;
  /**
   * Identifies which search backend produced the score (e.g. `postgres`, `mongo`, `qdrant`, `pgvector`).
   */
  kind?: "postgres" | "mongo" | "qdrant" | "pgvector";
  highlights?: string;
  /**
   * The matched entry. Only included when includeEntry is true in the request.
   */
  entry?: Entry;
};

/**
 * Represents a pending ownership transfer request.
 * Transfers are always "pending" while they exist; accepted/rejected transfers
 * are hard deleted from the database.
 */
export type OwnershipTransfer = {
  /**
   * Unique identifier for the transfer.
   */
  id: string;
  /**
   * The conversation being transferred.
   */
  conversationId: string;
  /**
   * Title of the conversation (for display purposes).
   */
  conversationTitle?: string;
  /**
   * Current owner initiating the transfer.
   */
  fromUserId: string;
  /**
   * Proposed new owner (recipient).
   */
  toUserId: string;
  /**
   * When the transfer was initiated.
   */
  createdAt: string;
};

export type CreateOwnershipTransferRequest = {
  /**
   * The conversation to transfer ownership of.
   */
  conversationId: string;
  /**
   * User ID of the proposed new owner. Must be an existing member.
   */
  newOwnerUserId: string;
};

export type GetCapabilitiesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/capabilities";
};

export type GetCapabilitiesErrors = {
  /**
   * Authentication required.
   */
  401: unknown;
  /**
   * Client context or admin/auditor role required.
   */
  403: unknown;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetCapabilitiesError = GetCapabilitiesErrors[keyof GetCapabilitiesErrors];

export type GetCapabilitiesResponses = {
  /**
   * Capability summary for the current client.
   */
  200: CapabilitiesResponse;
};

export type GetCapabilitiesResponse = GetCapabilitiesResponses[keyof GetCapabilitiesResponses];

export type ListConversationsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Listing mode for conversations. Controls which conversations are returned
     * from each fork tree (conversation group).
     * - `all`: include all conversations the user can access (roots and forks).
     * - `roots`: only include root conversations (conversations that are not forks).
     * - `latest-fork`: include only the most recently updated conversation per fork tree.
     * This is useful for showing a single representative conversation from each tree.
     */
    mode?: "all" | "roots" | "latest-fork";
    /**
     * Started-conversation ancestry filter.
     * - `roots`: include only top-level conversations not started from another conversation.
     * - `children`: include only conversations started from another conversation.
     * - `all`: include both root and child conversations.
     */
    ancestry?: "all" | "roots" | "children";
    /**
     * Cursor for pagination; returns items after this conversation id.
     */
    afterCursor?: string;
    /**
     * Maximum number of conversations to return.
     */
    limit?: number;
    /**
     * Optional text query for basic title/metadata search.
     */
    query?: string;
    /**
     * Controls whether archived conversations are excluded, included, or returned exclusively.
     */
    archived?: "exclude" | "include" | "only";
  };
  url: "/v1/conversations";
};

export type ListConversationsErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type ListConversationsError = ListConversationsErrors[keyof ListConversationsErrors];

export type ListConversationsResponses = {
  /**
   * A list of conversations.
   */
  200: {
    data?: Array<ConversationSummary>;
    afterCursor?: string;
  };
};

export type ListConversationsResponse = ListConversationsResponses[keyof ListConversationsResponses];

export type CreateConversationData = {
  body: CreateConversationRequest;
  path?: never;
  query?: never;
  url: "/v1/conversations";
};

export type CreateConversationErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type CreateConversationError = CreateConversationErrors[keyof CreateConversationErrors];

export type CreateConversationResponses = {
  /**
   * The created conversation.
   */
  201: Conversation;
};

export type CreateConversationResponse = CreateConversationResponses[keyof CreateConversationResponses];

export type GetConversationData = {
  body?: never;
  path: {
    /**
     * Conversation identifier.
     */
    conversationId: string;
  };
  query?: never;
  url: "/v1/conversations/{conversationId}";
};

export type GetConversationErrors = {
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetConversationError = GetConversationErrors[keyof GetConversationErrors];

export type GetConversationResponses = {
  /**
   * The conversation.
   */
  200: Conversation;
};

export type GetConversationResponse = GetConversationResponses[keyof GetConversationResponses];

export type UpdateConversationData = {
  body: UpdateConversationRequest;
  path: {
    /**
     * Conversation identifier.
     */
    conversationId: string;
  };
  query?: never;
  url: "/v1/conversations/{conversationId}";
};

export type UpdateConversationErrors = {
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type UpdateConversationError = UpdateConversationErrors[keyof UpdateConversationErrors];

export type UpdateConversationResponses = {
  /**
   * The updated conversation.
   */
  200: Conversation;
};

export type UpdateConversationResponse = UpdateConversationResponses[keyof UpdateConversationResponses];

export type ListConversationEntriesData = {
  body?: never;
  path: {
    /**
     * Conversation identifier.
     */
    conversationId: string;
  };
  query?: {
    /**
     * Cursor for pagination; returns entries after this entry id (UUID format).
     */
    afterCursor?: string;
    /**
     * Cursor for backward pagination; returns up to `limit` entries strictly
     * before this entry in the caller-visible order. Results remain chronological
     * (ascending). Mutually exclusive with `afterCursor` and `tail=true`.
     */
    beforeCursor?: string;
    /**
     * When `true`, returns the last `limit` entries in the caller-visible order
     * (newest page). Results remain chronological (ascending). Mutually exclusive
     * with `afterCursor` and `beforeCursor`.
     */
    tail?: boolean;
    /**
     * Upper-bound entry id (UUID format). When set, only entries at or
     * before this entry in the caller-visible conversation order are
     * returned. This is useful with `channel=context` and `epoch` to
     * reconstruct the agent context as of a specific history entry.
     */
    upToEntryId?: string;
    limit?: number;
    /**
     * Channel of entries to return. Defaults to `history` for the
     * user-visible conversation; `context` returns agent-managed context entries
     * scoped to the calling client id.
     */
    channel?: Channel;
    /**
     * Optional epoch filter when listing the `context` channel. Valid values
     * are `latest`, `all`, or a numeric epoch identifier. Defaults to
     * `latest` when not provided. The epoch selection is scoped to the
     * calling client id.
     */
    epoch?: string;
    /**
     * When set, return only entries with `seq >= fromSeq`, ordered by `seq` ASC.
     * Entries without a `seq` are excluded. When omitted the default
     * ordering is `createdAt` ASC, `seq` ASC NULLS FIRST, then `id` ASC.
     */
    fromSeq?: number;
    /**
     * Controls which fork entries to include. `none` (default) follows the
     * fork ancestry path, returning entries from the target conversation
     * and its ancestors up to fork points. `all` returns entries from all
     * forks in the conversation group, useful for debugging or getting a
     * complete picture of all activity across forks.
     */
    forks?: "none" | "all";
  };
  url: "/v1/conversations/{conversationId}/entries";
};

export type ListConversationEntriesErrors = {
  /**
   * Bad request
   */
  400: ErrorResponse;
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type ListConversationEntriesError = ListConversationEntriesErrors[keyof ListConversationEntriesErrors];

export type ListConversationEntriesResponses = {
  /**
   * A list of entries.
   */
  200: {
    data?: Array<Entry>;
    /**
     * Pass as afterCursor to fetch the adjacent newer page. Null when no newer entries exist.
     */
    afterCursor?: string;
    /**
     * Pass as beforeCursor to fetch the adjacent older page. Null when no older entries exist.
     */
    beforeCursor?: string;
  };
};

export type ListConversationEntriesResponse = ListConversationEntriesResponses[keyof ListConversationEntriesResponses];

export type AppendConversationEntryData = {
  body: CreateEntryRequest;
  path: {
    /**
     * Conversation identifier.
     */
    conversationId: string;
  };
  query?: never;
  url: "/v1/conversations/{conversationId}/entries";
};

export type AppendConversationEntryErrors = {
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  409: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type AppendConversationEntryError = AppendConversationEntryErrors[keyof AppendConversationEntryErrors];

export type AppendConversationEntryResponses = {
  /**
   * The created entry.
   */
  201: Entry;
};

export type AppendConversationEntryResponse = AppendConversationEntryResponses[keyof AppendConversationEntryResponses];

export type SyncConversationContextData = {
  body: CreateEntryRequest;
  path: {
    /**
     * Conversation identifier.
     */
    conversationId: string;
  };
  query?: never;
  url: "/v1/conversations/{conversationId}/entries/sync";
};

export type SyncConversationContextErrors = {
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type SyncConversationContextError = SyncConversationContextErrors[keyof SyncConversationContextErrors];

export type SyncConversationContextResponses = {
  /**
   * Result of the sync operation.
   */
  200: SyncEntryResponse;
};

export type SyncConversationContextResponse = SyncConversationContextResponses[keyof SyncConversationContextResponses];

export type ListConversationForksData = {
  body?: never;
  path: {
    /**
     * Conversation identifier.
     */
    conversationId: string;
  };
  query?: never;
  url: "/v1/conversations/{conversationId}/forks";
};

export type ListConversationForksErrors = {
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type ListConversationForksError = ListConversationForksErrors[keyof ListConversationForksErrors];

export type ListConversationForksResponses = {
  /**
   * Fork navigation for the requested conversation.
   */
  200: ConversationForkNavigation;
};

export type ListConversationForksResponse = ListConversationForksResponses[keyof ListConversationForksResponses];

export type ListConversationChildrenData = {
  body?: never;
  path: {
    conversationId: string;
  };
  query?: {
    afterCursor?: string;
    limit?: number;
  };
  url: "/v1/conversations/{conversationId}/children";
};

export type ListConversationChildrenErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type ListConversationChildrenError = ListConversationChildrenErrors[keyof ListConversationChildrenErrors];

export type ListConversationChildrenResponses = {
  /**
   * A list of direct child conversations.
   */
  200: {
    data?: Array<ChildConversationSummary>;
    afterCursor?: string;
  };
};

export type ListConversationChildrenResponse =
  ListConversationChildrenResponses[keyof ListConversationChildrenResponses];

export type DeleteConversationResponseData = {
  body?: never;
  path: {
    /**
     * Conversation identifier.
     */
    conversationId: string;
  };
  query?: never;
  url: "/v1/conversations/{conversationId}/response";
};

export type DeleteConversationResponseErrors = {
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  409: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type DeleteConversationResponseError = DeleteConversationResponseErrors[keyof DeleteConversationResponseErrors];

export type DeleteConversationResponseResponses = {
  /**
   * Cancel request accepted.
   */
  200: unknown;
};

export type ListPendingTransfersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter by user's role in the transfer.
     */
    role?: "sender" | "recipient" | "all";
    /**
     * Cursor for pagination; returns items after this transfer id (UUID format).
     */
    afterCursor?: string;
    /**
     * Maximum number of transfers to return.
     */
    limit?: number;
  };
  url: "/v1/ownership-transfers";
};

export type ListPendingTransfersErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type ListPendingTransfersError = ListPendingTransfersErrors[keyof ListPendingTransfersErrors];

export type ListPendingTransfersResponses = {
  /**
   * List of pending transfers.
   */
  200: {
    data?: Array<OwnershipTransfer>;
    afterCursor?: string;
  };
};

export type ListPendingTransfersResponse = ListPendingTransfersResponses[keyof ListPendingTransfersResponses];

export type CreateOwnershipTransferData = {
  body: CreateOwnershipTransferRequest;
  path?: never;
  query?: never;
  url: "/v1/ownership-transfers";
};

export type CreateOwnershipTransferErrors = {
  /**
   * Error response
   */
  400: ErrorResponse;
  /**
   * Error response
   */
  403: ErrorResponse;
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * A pending transfer already exists for this conversation.
   */
  409: {
    code: string;
    error: string;
    /**
     * Request correlation identifier, also returned in the X-Request-ID header.
     */
    requestId: string;
    /**
     * Structured non-sensitive error details.
     */
    details?: {
      [key: string]: unknown;
    };
  };
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type CreateOwnershipTransferError = CreateOwnershipTransferErrors[keyof CreateOwnershipTransferErrors];

export type CreateOwnershipTransferResponses = {
  /**
   * Transfer initiated successfully.
   */
  201: OwnershipTransfer;
};

export type CreateOwnershipTransferResponse = CreateOwnershipTransferResponses[keyof CreateOwnershipTransferResponses];

export type DeleteTransferData = {
  body?: never;
  path: {
    /**
     * Transfer identifier (UUID format).
     */
    transferId: string;
  };
  query?: never;
  url: "/v1/ownership-transfers/{transferId}";
};

export type DeleteTransferErrors = {
  /**
   * Error response
   */
  403: ErrorResponse;
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type DeleteTransferError = DeleteTransferErrors[keyof DeleteTransferErrors];

export type DeleteTransferResponses = {
  /**
   * Transfer deleted successfully.
   */
  204: void;
};

export type DeleteTransferResponse = DeleteTransferResponses[keyof DeleteTransferResponses];

export type GetTransferData = {
  body?: never;
  path: {
    /**
     * Transfer identifier (UUID format).
     */
    transferId: string;
  };
  query?: never;
  url: "/v1/ownership-transfers/{transferId}";
};

export type GetTransferErrors = {
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetTransferError = GetTransferErrors[keyof GetTransferErrors];

export type GetTransferResponses = {
  /**
   * Transfer details.
   */
  200: OwnershipTransfer;
};

export type GetTransferResponse = GetTransferResponses[keyof GetTransferResponses];

export type AcceptTransferData = {
  body?: never;
  path: {
    /**
     * Transfer identifier (UUID format).
     */
    transferId: string;
  };
  query?: never;
  url: "/v1/ownership-transfers/{transferId}/accept";
};

export type AcceptTransferErrors = {
  /**
   * Error response
   */
  403: ErrorResponse;
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type AcceptTransferError = AcceptTransferErrors[keyof AcceptTransferErrors];

export type AcceptTransferResponses = {
  /**
   * Transfer accepted successfully. Ownership has been transferred.
   */
  204: void;
};

export type AcceptTransferResponse = AcceptTransferResponses[keyof AcceptTransferResponses];

export type ListConversationMembershipsData = {
  body?: never;
  path: {
    /**
     * Conversation identifier.
     */
    conversationId: string;
  };
  query?: {
    /**
     * Cursor for pagination; returns items after this user id.
     */
    afterCursor?: string;
    /**
     * Maximum number of memberships to return.
     */
    limit?: number;
  };
  url: "/v1/conversations/{conversationId}/memberships";
};

export type ListConversationMembershipsErrors = {
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type ListConversationMembershipsError =
  ListConversationMembershipsErrors[keyof ListConversationMembershipsErrors];

export type ListConversationMembershipsResponses = {
  /**
   * Memberships for the conversation.
   */
  200: {
    data?: Array<ConversationMembership>;
    afterCursor?: string;
  };
};

export type ListConversationMembershipsResponse =
  ListConversationMembershipsResponses[keyof ListConversationMembershipsResponses];

export type ShareConversationData = {
  body: ShareConversationRequest;
  path: {
    /**
     * Conversation identifier.
     */
    conversationId: string;
  };
  query?: never;
  url: "/v1/conversations/{conversationId}/memberships";
};

export type ShareConversationErrors = {
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type ShareConversationError = ShareConversationErrors[keyof ShareConversationErrors];

export type ShareConversationResponses = {
  /**
   * Created membership.
   */
  201: ConversationMembership;
};

export type ShareConversationResponse = ShareConversationResponses[keyof ShareConversationResponses];

export type DeleteConversationMembershipData = {
  body?: never;
  path: {
    /**
     * Conversation identifier.
     */
    conversationId: string;
    userId: string;
  };
  query?: never;
  url: "/v1/conversations/{conversationId}/memberships/{userId}";
};

export type DeleteConversationMembershipErrors = {
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type DeleteConversationMembershipError =
  DeleteConversationMembershipErrors[keyof DeleteConversationMembershipErrors];

export type DeleteConversationMembershipResponses = {
  /**
   * Membership removed.
   */
  204: void;
};

export type DeleteConversationMembershipResponse =
  DeleteConversationMembershipResponses[keyof DeleteConversationMembershipResponses];

export type UpdateConversationMembershipData = {
  body: {
    accessLevel?: AccessLevel;
  };
  path: {
    /**
     * Conversation identifier.
     */
    conversationId: string;
    userId: string;
  };
  query?: never;
  url: "/v1/conversations/{conversationId}/memberships/{userId}";
};

export type UpdateConversationMembershipErrors = {
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type UpdateConversationMembershipError =
  UpdateConversationMembershipErrors[keyof UpdateConversationMembershipErrors];

export type UpdateConversationMembershipResponses = {
  /**
   * Updated membership.
   */
  200: ConversationMembership;
};

export type UpdateConversationMembershipResponse =
  UpdateConversationMembershipResponses[keyof UpdateConversationMembershipResponses];

export type SearchConversationsData = {
  body: SearchConversationsRequest;
  path?: never;
  query?: never;
  url: "/v1/conversations/search";
};

export type SearchConversationsErrors = {
  /**
   * Requested search type is not available on this server
   */
  501: SearchTypeUnavailableError;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type SearchConversationsError = SearchConversationsErrors[keyof SearchConversationsErrors];

export type SearchConversationsResponses = {
  /**
   * Search results.
   */
  200: {
    data?: Array<SearchResult>;
    afterCursor?: string;
  };
};

export type SearchConversationsResponse = SearchConversationsResponses[keyof SearchConversationsResponses];

export type IndexConversationsData = {
  body: Array<IndexEntryRequest>;
  path?: never;
  query?: never;
  url: "/v1/conversations/index";
};

export type IndexConversationsErrors = {
  /**
   * Error response
   */
  403: ErrorResponse;
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type IndexConversationsError = IndexConversationsErrors[keyof IndexConversationsErrors];

export type IndexConversationsResponses = {
  /**
   * Entries indexed successfully.
   */
  200: IndexConversationsResponse;
};

export type IndexConversationsResponse2 = IndexConversationsResponses[keyof IndexConversationsResponses];

export type ListUnindexedEntriesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum number of entries to return.
     */
    limit?: number;
    /**
     * Pagination cursor from previous response.
     */
    afterCursor?: string;
  };
  url: "/v1/conversations/unindexed";
};

export type ListUnindexedEntriesErrors = {
  /**
   * Error response
   */
  403: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type ListUnindexedEntriesError = ListUnindexedEntriesErrors[keyof ListUnindexedEntriesErrors];

export type ListUnindexedEntriesResponses = {
  /**
   * Paginated list of unindexed entries.
   */
  200: UnindexedEntriesResponse;
};

export type ListUnindexedEntriesResponse = ListUnindexedEntriesResponses[keyof ListUnindexedEntriesResponses];

export type GetMemoryData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Namespace segments. Repeat once per segment.
     */
    ns: Array<string>;
    key: string;
    /**
     * Include usage counters for the requested memory.
     */
    include_usage?: boolean;
    /**
     * Controls whether archived memories are excluded, included, or returned exclusively.
     */
    archived?: "exclude" | "include" | "only";
  };
  url: "/v1/memories";
};

export type GetMemoryErrors = {
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetMemoryError = GetMemoryErrors[keyof GetMemoryErrors];

export type GetMemoryResponses = {
  /**
   * Memory found.
   */
  200: MemoryItem;
};

export type GetMemoryResponse = GetMemoryResponses[keyof GetMemoryResponses];

export type UpdateMemoryData = {
  body: UpdateMemoryRequest;
  path?: never;
  query: {
    /**
     * Namespace segments. Repeat once per segment.
     */
    ns: Array<string>;
    key: string;
  };
  url: "/v1/memories";
};

export type UpdateMemoryErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type UpdateMemoryError = UpdateMemoryErrors[keyof UpdateMemoryErrors];

export type UpdateMemoryResponses = {
  /**
   * Memory updated.
   */
  204: void;
};

export type UpdateMemoryResponse = UpdateMemoryResponses[keyof UpdateMemoryResponses];

export type PutMemoryData = {
  body: PutMemoryRequest;
  path?: never;
  query?: never;
  url: "/v1/memories";
};

export type PutMemoryErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type PutMemoryError = PutMemoryErrors[keyof PutMemoryErrors];

export type PutMemoryResponses = {
  /**
   * Memory stored.
   */
  200: MemoryWriteResult;
};

export type PutMemoryResponse = PutMemoryResponses[keyof PutMemoryResponses];

export type SearchMemoriesData = {
  body: SearchMemoriesRequest;
  path?: never;
  query?: never;
  url: "/v1/memories/search";
};

export type SearchMemoriesErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type SearchMemoriesError = SearchMemoriesErrors[keyof SearchMemoriesErrors];

export type SearchMemoriesResponses = {
  /**
   * Search results.
   */
  200: SearchMemoriesResponse;
};

export type SearchMemoriesResponse2 = SearchMemoriesResponses[keyof SearchMemoriesResponses];

export type ListMemoryNamespacesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Namespace prefix segments. Repeat once per segment.
     */
    prefix?: Array<string>;
    /**
     * Namespace suffix segments. Repeat once per segment.
     */
    suffix?: Array<string>;
    max_depth?: number;
    /**
     * Controls whether archived memories are excluded, included, or returned exclusively.
     */
    archived?: "exclude" | "include" | "only";
  };
  url: "/v1/memories/namespaces";
};

export type ListMemoryNamespacesErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type ListMemoryNamespacesError = ListMemoryNamespacesErrors[keyof ListMemoryNamespacesErrors];

export type ListMemoryNamespacesResponses = {
  /**
   * Distinct namespaces.
   */
  200: ListMemoryNamespacesResponse;
};

export type ListMemoryNamespacesResponse2 = ListMemoryNamespacesResponses[keyof ListMemoryNamespacesResponses];

export type ListMemoryEventsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Namespace prefix segments. Repeat once per segment.
     */
    ns?: Array<string>;
    /**
     * Filter by event kind. Repeat to include multiple. Values: add, update, expired.
     */
    kinds?: Array<"add" | "update" | "expired">;
    /**
     * Return events with occurred_at strictly after this ISO 8601 timestamp.
     */
    after?: string;
    /**
     * Return events with occurred_at strictly before this ISO 8601 timestamp.
     */
    before?: string;
    /**
     * Opaque cursor from a previous response for pagination.
     */
    after_cursor?: string;
    limit?: number;
  };
  url: "/v1/memories/events";
};

export type ListMemoryEventsErrors = {
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type ListMemoryEventsError = ListMemoryEventsErrors[keyof ListMemoryEventsErrors];

export type ListMemoryEventsResponses = {
  /**
   * Memory event page.
   */
  200: ListMemoryEventsResponse;
};

export type ListMemoryEventsResponse2 = ListMemoryEventsResponses[keyof ListMemoryEventsResponses];

export type UploadAttachmentData = {
  body: CreateFromUrlRequest;
  path?: never;
  query?: {
    /**
     * ISO 8601 duration for how long the unlinked attachment should persist.
     * Defaults to 1 hour. Maximum 24 hours. Only used for multipart uploads.
     */
    expiresIn?: string;
  };
  url: "/v1/attachments";
};

export type UploadAttachmentErrors = {
  /**
   * Error response
   */
  400: ErrorResponse;
  /**
   * File too large.
   */
  413: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type UploadAttachmentError = UploadAttachmentErrors[keyof UploadAttachmentErrors];

export type UploadAttachmentResponses = {
  /**
   * Attachment created successfully.
   */
  201: AttachmentUploadResponse;
};

export type UploadAttachmentResponse = UploadAttachmentResponses[keyof UploadAttachmentResponses];

export type DeleteAttachmentData = {
  body?: never;
  path: {
    /**
     * Attachment identifier (UUID format).
     */
    id: string;
  };
  query?: never;
  url: "/v1/attachments/{id}";
};

export type DeleteAttachmentErrors = {
  /**
   * Error response
   */
  403: ErrorResponse;
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  409: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type DeleteAttachmentError = DeleteAttachmentErrors[keyof DeleteAttachmentErrors];

export type DeleteAttachmentResponses = {
  /**
   * Attachment deleted.
   */
  204: void;
};

export type DeleteAttachmentResponse = DeleteAttachmentResponses[keyof DeleteAttachmentResponses];

export type GetAttachmentData = {
  body?: never;
  path: {
    /**
     * Attachment identifier (UUID format).
     */
    id: string;
  };
  query?: {
    /**
     * Controls the Content-Disposition header. Use `inline` to display the attachment
     * in the browser (e.g., images, PDFs), or `attachment` to force download.
     * If not specified, the Content-Disposition header is not set, allowing the browser
     * to use its default behavior based on content type.
     */
    disposition?: "inline" | "attachment";
  };
  url: "/v1/attachments/{id}";
};

export type GetAttachmentErrors = {
  /**
   * Error response
   */
  403: ErrorResponse;
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetAttachmentError = GetAttachmentErrors[keyof GetAttachmentErrors];

export type GetAttachmentResponses = {
  /**
   * Attachment binary content.
   */
  200: Blob | File;
};

export type GetAttachmentResponse = GetAttachmentResponses[keyof GetAttachmentResponses];

export type GetAttachmentDownloadUrlData = {
  body?: never;
  path: {
    /**
     * Attachment identifier (UUID format).
     */
    id: string;
  };
  query?: {
    /**
     * Controls the Content-Disposition header on the returned download URL.
     * Use `inline` to display the attachment in the browser (e.g., images, PDFs),
     * or `attachment` to force download. If not specified, the
     * Content-Disposition header is not set, allowing the browser to use its
     * default behavior based on content type.
     */
    disposition?: "inline" | "attachment";
  };
  url: "/v1/attachments/{id}/download-url";
};

export type GetAttachmentDownloadUrlErrors = {
  /**
   * Error response
   */
  403: ErrorResponse;
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type GetAttachmentDownloadUrlError = GetAttachmentDownloadUrlErrors[keyof GetAttachmentDownloadUrlErrors];

export type GetAttachmentDownloadUrlResponses = {
  /**
   * Signed download URL.
   */
  200: AttachmentDownloadUrlResponse;
};

export type GetAttachmentDownloadUrlResponse =
  GetAttachmentDownloadUrlResponses[keyof GetAttachmentDownloadUrlResponses];

export type DownloadAttachmentByTokenData = {
  body?: never;
  path: {
    /**
     * Signed download token.
     */
    token: string;
    /**
     * Filename for the download (used in Content-Disposition).
     */
    filename: string;
  };
  query?: {
    /**
     * Controls the Content-Disposition header. Use `inline` to display the attachment
     * in the browser (e.g., images, PDFs), or `attachment` to force download.
     * If not specified, the Content-Disposition header is not set, allowing the browser
     * to use its default behavior based on content type.
     */
    disposition?: "inline" | "attachment";
  };
  url: "/v1/attachments/download/{token}/{filename}";
};

export type DownloadAttachmentByTokenErrors = {
  /**
   * Invalid or expired token.
   */
  403: unknown;
  /**
   * Resource not found
   */
  404: ErrorResponse;
  /**
   * Error response
   */
  default: ErrorResponse;
};

export type DownloadAttachmentByTokenError = DownloadAttachmentByTokenErrors[keyof DownloadAttachmentByTokenErrors];

export type DownloadAttachmentByTokenResponses = {
  /**
   * Attachment binary content.
   */
  200: Blob | File;
};

export type DownloadAttachmentByTokenResponse =
  DownloadAttachmentByTokenResponses[keyof DownloadAttachmentByTokenResponses];

export type SubscribeEventsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Comma-separated event kinds to filter (conversation, entry, response, membership).
     */
    kinds?: string;
    /**
     * Replay events after the provided durable cursor. Requires the outbox feature to be enabled.
     */
    after?: string;
    /**
     * Event payload detail level.
     */
    detail?: "summary" | "full";
    /**
     * Comma-separated entry channels to deliver for entry events. Defaults to history.
     */
    entry_channels?: string;
    /**
     * Comma-separated entry content types to deliver for entry events. Omit to allow any.
     */
    entry_content_types?: string;
    /**
     * Comma-separated entry roles to deliver for entry events. Omit to allow any.
     */
    entry_roles?: string;
  };
  url: "/v1/events";
};

export type SubscribeEventsErrors = {
  /**
   * Authentication required.
   */
  401: unknown;
  /**
   * Too many SSE connections for this user.
   */
  429: unknown;
};

export type SubscribeEventsResponses = {
  /**
   * Newline-delimited SSE events.
   */
  200: string;
};

export type SubscribeEventsResponse = SubscribeEventsResponses[keyof SubscribeEventsResponses];

export type AdminSubscribeEventsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Optional reason for subscribing, logged for audit when present. Servers configured to require admin justifications reject requests without one.
     */
    justification?: string;
    /**
     * Comma-separated event kinds to filter.
     */
    kinds?: string;
    /**
     * Replay events after the provided durable cursor. Requires the outbox feature to be enabled.
     */
    after?: string;
    /**
     * Event payload detail level.
     */
    detail?: "summary" | "full";
    /**
     * Comma-separated entry channels to deliver for entry events. Defaults to history.
     */
    entry_channels?: string;
    /**
     * Comma-separated entry content types to deliver for entry events. Omit to allow any.
     */
    entry_content_types?: string;
    /**
     * Comma-separated entry roles to deliver for entry events. Omit to allow any.
     */
    entry_roles?: string;
  };
  url: "/v1/admin/events";
};

export type AdminSubscribeEventsErrors = {
  /**
   * Invalid request parameters, including missing justification when admin justification enforcement is enabled.
   */
  400: unknown;
  /**
   * Authentication required.
   */
  401: unknown;
  /**
   * Admin or auditor role required.
   */
  403: unknown;
};

export type AdminSubscribeEventsResponses = {
  /**
   * SSE event stream opened successfully.
   */
  200: string;
};

export type AdminSubscribeEventsResponse = AdminSubscribeEventsResponses[keyof AdminSubscribeEventsResponses];
