package testutil_test

import (
	"context"
	"net/http"
	"testing"

	pb "github.com/chirino/memory-service/internal/generated/pb/memory/v1"
	"github.com/chirino/memory-service/internal/tracing/testutil"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/trace"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

// 1a. Start a span with no parent under ParentBased(NeverSample()).
// Assert whether the returned span context IsValid() and whether it carries a non-zero trace ID.
func TestCharacterization_1a_NoParentTracerStart(t *testing.T) {
	harness := testutil.NewTestHarness()
	defer func() { _ = harness.Shutdown(context.Background()) }()

	tracer := harness.Provider.Tracer("test-tracer")
	ctx, span := tracer.Start(context.Background(), "test-span")
	defer span.End()

	sc := span.SpanContext()
	t.Logf("1a: span.IsRecording() = %v", span.IsRecording())
	t.Logf("1a: SpanContext.IsValid() = %v", sc.IsValid())
	t.Logf("1a: SpanContext.TraceID() = %s", sc.TraceID().String())
	t.Logf("1a: SpanContext.SpanID() = %s", sc.SpanID().String())
	t.Logf("1a: SpanContext.IsSampled() = %v", sc.IsSampled())

	// Prove the claim: SDK generates a valid traceID/spanID even on Drop decision
	require.True(t, sc.IsValid(), "Expected SpanContext.IsValid() to be TRUE even without parent")
	require.True(t, sc.TraceID().IsValid(), "Expected valid TraceID generated by SDK")
	require.False(t, sc.IsSampled(), "Expected IsSampled() to be FALSE under NeverSample()")
	require.False(t, span.IsRecording(), "Expected non-recording span under NeverSample()")

	// Also check context
	ctxSC := trace.SpanContextFromContext(ctx)
	require.True(t, ctxSC.IsValid())
	require.Equal(t, sc.TraceID(), ctxSC.TraceID())
}

// 1b. Send a request with no inbound traceparent through otelhttp.NewTransport.
// Assert exactly what the outbound request carries under two propagator configurations.
func TestCharacterization_1b_NoInboundOtelHTTPTransport(t *testing.T) {
	harness := testutil.NewTestHarness()
	defer func() { _ = harness.Shutdown(context.Background()) }()

	t.Run("plain propagator injects phantom traceparent", func(t *testing.T) {
		downstream := testutil.NewDownstreamRecorder()
		defer downstream.Close()

		// Use the raw TraceContext propagator — no ParticipatingPropagator gate.
		client := &http.Client{
			Transport: otelhttp.NewTransport(
				http.DefaultTransport,
				otelhttp.WithTracerProvider(harness.Provider),
				otelhttp.WithPropagators(propagation.TraceContext{}),
			),
		}

		req, err := http.NewRequestWithContext(context.Background(), http.MethodGet, downstream.Server.URL, nil)
		require.NoError(t, err)

		resp, err := client.Do(req)
		require.NoError(t, err)
		defer resp.Body.Close()

		lastHeader := downstream.LastHeader()
		require.NotNil(t, lastHeader)
		outboundTraceparent := lastHeader.Get("Traceparent")
		t.Logf("1b plain: Outbound traceparent header = %q", outboundTraceparent)

		// Proves the root SDK claim: otelhttp.NewTransport calls tracer.Start unconditionally,
		// mints a new span context, and the plain propagator injects it.
		require.NotEmpty(t, outboundTraceparent, "plain propagator: otelhttp.NewTransport injects a freshly minted phantom traceparent")
	})

	t.Run("ParticipatingPropagator suppresses phantom traceparent", func(t *testing.T) {
		downstream := testutil.NewDownstreamRecorder()
		defer downstream.Close()

		// ParticipatingPropagator.Inject is a no-op unless IsParticipating(ctx) is true.
		client := &http.Client{
			Transport: otelhttp.NewTransport(
				http.DefaultTransport,
				otelhttp.WithTracerProvider(harness.Provider),
				otelhttp.WithPropagators(harness.Propagator),
			),
		}

		req, err := http.NewRequestWithContext(context.Background(), http.MethodGet, downstream.Server.URL, nil)
		require.NoError(t, err)

		resp, err := client.Do(req)
		require.NoError(t, err)
		defer resp.Body.Close()

		require.Equal(t, 1, downstream.CallCount(), "downstream must be reached")

		lastHeader := downstream.LastHeader()
		require.NotNil(t, lastHeader)
		outboundTraceparent := lastHeader.Get("Traceparent")
		t.Logf("1b participating: Outbound traceparent header = %q", outboundTraceparent)

		// ParticipatingPropagator suppresses the phantom inject on untraced requests.
		require.Empty(t, outboundTraceparent, "ParticipatingPropagator must not inject traceparent on untraced request")
	})
}

type dummySystemService struct {
	pb.UnimplementedSystemServiceServer
	extractedTraceID string
	extractedSpanID  string
	extractedSampled bool
}

func (s *dummySystemService) GetHealth(ctx context.Context, req *emptypb.Empty) (*pb.HealthResponse, error) {
	sc := trace.SpanContextFromContext(ctx)
	if sc.IsValid() {
		s.extractedTraceID = sc.TraceID().String()
		s.extractedSpanID = sc.SpanID().String()
		s.extractedSampled = sc.IsSampled()
	}
	return &pb.HealthResponse{Status: "ok"}, nil
}

// 1c. Send an RPC with no inbound metadata through otelgrpc.NewServerHandler.
// Assert what lands in the context, and what SetTraceContext would therefore read.
func TestCharacterization_1c_NoInboundOtelGRPCServerHandler(t *testing.T) {
	harness := testutil.NewTestHarness()
	defer func() { _ = harness.Shutdown(context.Background()) }()

	server := &dummySystemService{}
	grpcHarness := testutil.NewGRPCBufConnHarness(
		grpc.StatsHandler(otelgrpc.NewServerHandler(
			otelgrpc.WithTracerProvider(harness.Provider),
			otelgrpc.WithPropagators(harness.Propagator),
		)),
	)
	defer grpcHarness.Close()

	pb.RegisterSystemServiceServer(grpcHarness.Server, server)
	go func() { _ = grpcHarness.Server.Serve(grpcHarness.Listener) }()

	conn, err := grpcHarness.Dial(context.Background())
	require.NoError(t, err)
	defer conn.Close()

	client := pb.NewSystemServiceClient(conn)
	_, err = client.GetHealth(context.Background(), &emptypb.Empty{})
	require.NoError(t, err)

	t.Logf("1c: gRPC Server extracted TraceID = %q", server.extractedTraceID)
	t.Logf("1c: gRPC Server extracted SpanID = %q", server.extractedSpanID)
	t.Logf("1c: gRPC Server extracted Sampled = %v", server.extractedSampled)

	// Proves claim (c): otelgrpc.NewServerHandler starts a span, mints a phantom trace ID in context!
	require.NotEmpty(t, server.extractedTraceID, "otelgrpc.NewServerHandler puts a freshly minted phantom trace ID into ctx!")
}
