# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import memory_service_pb2 as memory_dot_v1_dot_memory__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in memory/v1/memory_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SystemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealth = channel.unary_unary(
                '/memory.v1.SystemService/GetHealth',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.HealthResponse.FromString,
                _registered_method=True)


class SystemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.v1.SystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.v1.SystemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.SystemService/GetHealth',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConversationsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListConversations = channel.unary_unary(
                '/memory.v1.ConversationsService/ListConversations',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.ListConversationsRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.ListConversationsResponse.FromString,
                _registered_method=True)
        self.CreateConversation = channel.unary_unary(
                '/memory.v1.ConversationsService/CreateConversation',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.CreateConversationRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.Conversation.FromString,
                _registered_method=True)
        self.GetConversation = channel.unary_unary(
                '/memory.v1.ConversationsService/GetConversation',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.GetConversationRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.Conversation.FromString,
                _registered_method=True)
        self.UpdateConversation = channel.unary_unary(
                '/memory.v1.ConversationsService/UpdateConversation',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.UpdateConversationRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.Conversation.FromString,
                _registered_method=True)
        self.DeleteConversation = channel.unary_unary(
                '/memory.v1.ConversationsService/DeleteConversation',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.DeleteConversationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListForks = channel.unary_unary(
                '/memory.v1.ConversationsService/ListForks',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.ListForksRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.ListForksResponse.FromString,
                _registered_method=True)


class ConversationsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListConversations(self, request, context):
        """ListConversations returns conversations the user has access to.
        The mode parameter controls which conversations from each fork tree are returned.
        See ConversationListMode for available modes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConversation(self, request, context):
        """DeleteConversation deletes a conversation. Deleting a conversation deletes all conversations in the same fork tree (the root conversation and all its forks). Memberships and entries associated with these conversations are also deleted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListForks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConversationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConversations,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.ListConversationsRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.ListConversationsResponse.SerializeToString,
            ),
            'CreateConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConversation,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.CreateConversationRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.Conversation.SerializeToString,
            ),
            'GetConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversation,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.GetConversationRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.Conversation.SerializeToString,
            ),
            'UpdateConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConversation,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.UpdateConversationRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.Conversation.SerializeToString,
            ),
            'DeleteConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConversation,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.DeleteConversationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListForks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListForks,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.ListForksRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.ListForksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.v1.ConversationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.v1.ConversationsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConversationsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.ConversationsService/ListConversations',
            memory_dot_v1_dot_memory__service__pb2.ListConversationsRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.ListConversationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.ConversationsService/CreateConversation',
            memory_dot_v1_dot_memory__service__pb2.CreateConversationRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.Conversation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.ConversationsService/GetConversation',
            memory_dot_v1_dot_memory__service__pb2.GetConversationRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.Conversation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.ConversationsService/UpdateConversation',
            memory_dot_v1_dot_memory__service__pb2.UpdateConversationRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.Conversation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.ConversationsService/DeleteConversation',
            memory_dot_v1_dot_memory__service__pb2.DeleteConversationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListForks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.ConversationsService/ListForks',
            memory_dot_v1_dot_memory__service__pb2.ListForksRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.ListForksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConversationMembershipsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListMemberships = channel.unary_unary(
                '/memory.v1.ConversationMembershipsService/ListMemberships',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.ListMembershipsRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.ListMembershipsResponse.FromString,
                _registered_method=True)
        self.ShareConversation = channel.unary_unary(
                '/memory.v1.ConversationMembershipsService/ShareConversation',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.ShareConversationRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.ConversationMembership.FromString,
                _registered_method=True)
        self.UpdateMembership = channel.unary_unary(
                '/memory.v1.ConversationMembershipsService/UpdateMembership',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.UpdateMembershipRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.ConversationMembership.FromString,
                _registered_method=True)
        self.DeleteMembership = channel.unary_unary(
                '/memory.v1.ConversationMembershipsService/DeleteMembership',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.DeleteMembershipRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ConversationMembershipsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListMemberships(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMembership(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMembership(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConversationMembershipsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListMemberships': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMemberships,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.ListMembershipsRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.ListMembershipsResponse.SerializeToString,
            ),
            'ShareConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareConversation,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.ShareConversationRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.ConversationMembership.SerializeToString,
            ),
            'UpdateMembership': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMembership,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.UpdateMembershipRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.ConversationMembership.SerializeToString,
            ),
            'DeleteMembership': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMembership,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.DeleteMembershipRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.v1.ConversationMembershipsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.v1.ConversationMembershipsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConversationMembershipsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListMemberships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.ConversationMembershipsService/ListMemberships',
            memory_dot_v1_dot_memory__service__pb2.ListMembershipsRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.ListMembershipsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.ConversationMembershipsService/ShareConversation',
            memory_dot_v1_dot_memory__service__pb2.ShareConversationRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.ConversationMembership.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMembership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.ConversationMembershipsService/UpdateMembership',
            memory_dot_v1_dot_memory__service__pb2.UpdateMembershipRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.ConversationMembership.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMembership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.ConversationMembershipsService/DeleteMembership',
            memory_dot_v1_dot_memory__service__pb2.DeleteMembershipRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OwnershipTransfersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListOwnershipTransfers = channel.unary_unary(
                '/memory.v1.OwnershipTransfersService/ListOwnershipTransfers',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.ListOwnershipTransfersRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.ListOwnershipTransfersResponse.FromString,
                _registered_method=True)
        self.GetOwnershipTransfer = channel.unary_unary(
                '/memory.v1.OwnershipTransfersService/GetOwnershipTransfer',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.GetOwnershipTransferRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.OwnershipTransfer.FromString,
                _registered_method=True)
        self.CreateOwnershipTransfer = channel.unary_unary(
                '/memory.v1.OwnershipTransfersService/CreateOwnershipTransfer',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.CreateOwnershipTransferRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.OwnershipTransfer.FromString,
                _registered_method=True)
        self.AcceptOwnershipTransfer = channel.unary_unary(
                '/memory.v1.OwnershipTransfersService/AcceptOwnershipTransfer',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.AcceptOwnershipTransferRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteOwnershipTransfer = channel.unary_unary(
                '/memory.v1.OwnershipTransfersService/DeleteOwnershipTransfer',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.DeleteOwnershipTransferRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class OwnershipTransfersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListOwnershipTransfers(self, request, context):
        """List pending ownership transfers for the current user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOwnershipTransfer(self, request, context):
        """Get a specific ownership transfer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOwnershipTransfer(self, request, context):
        """Create a new ownership transfer (initiates transfer to another user)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptOwnershipTransfer(self, request, context):
        """Accept an ownership transfer (recipient becomes owner, sender becomes manager)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteOwnershipTransfer(self, request, context):
        """Delete/cancel an ownership transfer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OwnershipTransfersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListOwnershipTransfers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOwnershipTransfers,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.ListOwnershipTransfersRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.ListOwnershipTransfersResponse.SerializeToString,
            ),
            'GetOwnershipTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOwnershipTransfer,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.GetOwnershipTransferRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.OwnershipTransfer.SerializeToString,
            ),
            'CreateOwnershipTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOwnershipTransfer,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.CreateOwnershipTransferRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.OwnershipTransfer.SerializeToString,
            ),
            'AcceptOwnershipTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptOwnershipTransfer,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.AcceptOwnershipTransferRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteOwnershipTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteOwnershipTransfer,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.DeleteOwnershipTransferRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.v1.OwnershipTransfersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.v1.OwnershipTransfersService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OwnershipTransfersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListOwnershipTransfers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.OwnershipTransfersService/ListOwnershipTransfers',
            memory_dot_v1_dot_memory__service__pb2.ListOwnershipTransfersRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.ListOwnershipTransfersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOwnershipTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.OwnershipTransfersService/GetOwnershipTransfer',
            memory_dot_v1_dot_memory__service__pb2.GetOwnershipTransferRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.OwnershipTransfer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOwnershipTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.OwnershipTransfersService/CreateOwnershipTransfer',
            memory_dot_v1_dot_memory__service__pb2.CreateOwnershipTransferRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.OwnershipTransfer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptOwnershipTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.OwnershipTransfersService/AcceptOwnershipTransfer',
            memory_dot_v1_dot_memory__service__pb2.AcceptOwnershipTransferRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteOwnershipTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.OwnershipTransfersService/DeleteOwnershipTransfer',
            memory_dot_v1_dot_memory__service__pb2.DeleteOwnershipTransferRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EntriesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEntries = channel.unary_unary(
                '/memory.v1.EntriesService/ListEntries',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.ListEntriesRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.ListEntriesResponse.FromString,
                _registered_method=True)
        self.AppendEntry = channel.unary_unary(
                '/memory.v1.EntriesService/AppendEntry',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.AppendEntryRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.Entry.FromString,
                _registered_method=True)
        self.SyncEntries = channel.unary_unary(
                '/memory.v1.EntriesService/SyncEntries',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.SyncEntriesRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.SyncEntriesResponse.FromString,
                _registered_method=True)


class EntriesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EntriesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEntries,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.ListEntriesRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.ListEntriesResponse.SerializeToString,
            ),
            'AppendEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntry,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.AppendEntryRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.Entry.SerializeToString,
            ),
            'SyncEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncEntries,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.SyncEntriesRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.SyncEntriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.v1.EntriesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.v1.EntriesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EntriesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.EntriesService/ListEntries',
            memory_dot_v1_dot_memory__service__pb2.ListEntriesRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.ListEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.EntriesService/AppendEntry',
            memory_dot_v1_dot_memory__service__pb2.AppendEntryRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.Entry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.EntriesService/SyncEntries',
            memory_dot_v1_dot_memory__service__pb2.SyncEntriesRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.SyncEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SearchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchConversations = channel.unary_unary(
                '/memory.v1.SearchService/SearchConversations',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.SearchEntriesRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.SearchEntriesResponse.FromString,
                _registered_method=True)
        self.IndexConversations = channel.unary_unary(
                '/memory.v1.SearchService/IndexConversations',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.IndexConversationsRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.IndexConversationsResponse.FromString,
                _registered_method=True)
        self.ListUnindexedEntries = channel.unary_unary(
                '/memory.v1.SearchService/ListUnindexedEntries',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.ListUnindexedEntriesRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.ListUnindexedEntriesResponse.FromString,
                _registered_method=True)


class SearchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchConversations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexConversations(self, request, context):
        """Index conversation entries for search. Requires indexer or admin role.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUnindexedEntries(self, request, context):
        """List entries needing indexing. Requires indexer or admin role.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchConversations,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.SearchEntriesRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.SearchEntriesResponse.SerializeToString,
            ),
            'IndexConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexConversations,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.IndexConversationsRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.IndexConversationsResponse.SerializeToString,
            ),
            'ListUnindexedEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUnindexedEntries,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.ListUnindexedEntriesRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.ListUnindexedEntriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.v1.SearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.v1.SearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SearchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.SearchService/SearchConversations',
            memory_dot_v1_dot_memory__service__pb2.SearchEntriesRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.SearchEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndexConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.SearchService/IndexConversations',
            memory_dot_v1_dot_memory__service__pb2.IndexConversationsRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.IndexConversationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUnindexedEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.SearchService/ListUnindexedEntries',
            memory_dot_v1_dot_memory__service__pb2.ListUnindexedEntriesRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.ListUnindexedEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ResponseRecorderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Record = channel.stream_unary(
                '/memory.v1.ResponseRecorderService/Record',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.RecordRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.RecordResponse.FromString,
                _registered_method=True)
        self.Replay = channel.unary_stream(
                '/memory.v1.ResponseRecorderService/Replay',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.ReplayRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.ReplayResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/memory.v1.ResponseRecorderService/Cancel',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.CancelRecordRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.CancelRecordResponse.FromString,
                _registered_method=True)
        self.IsEnabled = channel.unary_unary(
                '/memory.v1.ResponseRecorderService/IsEnabled',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.IsEnabledResponse.FromString,
                _registered_method=True)
        self.CheckRecordings = channel.unary_unary(
                '/memory.v1.ResponseRecorderService/CheckRecordings',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.CheckRecordingsRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.CheckRecordingsResponse.FromString,
                _registered_method=True)


class ResponseRecorderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Record(self, request_iterator, context):
        """Record response content for a conversation (client streaming, unary response)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replay(self, request, context):
        """Replay a recording of a conversation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Cancel an in-progress recording
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsEnabled(self, request, context):
        """Check if response recorder is enabled
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckRecordings(self, request, context):
        """Check which conversations have active recordings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResponseRecorderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Record': grpc.stream_unary_rpc_method_handler(
                    servicer.Record,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.RecordRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.RecordResponse.SerializeToString,
            ),
            'Replay': grpc.unary_stream_rpc_method_handler(
                    servicer.Replay,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.ReplayRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.ReplayResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.CancelRecordRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.CancelRecordResponse.SerializeToString,
            ),
            'IsEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.IsEnabled,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.IsEnabledResponse.SerializeToString,
            ),
            'CheckRecordings': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckRecordings,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.CheckRecordingsRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.CheckRecordingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.v1.ResponseRecorderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.v1.ResponseRecorderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResponseRecorderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Record(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/memory.v1.ResponseRecorderService/Record',
            memory_dot_v1_dot_memory__service__pb2.RecordRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.RecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/memory.v1.ResponseRecorderService/Replay',
            memory_dot_v1_dot_memory__service__pb2.ReplayRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.ReplayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.ResponseRecorderService/Cancel',
            memory_dot_v1_dot_memory__service__pb2.CancelRecordRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.CancelRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.ResponseRecorderService/IsEnabled',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.IsEnabledResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckRecordings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.ResponseRecorderService/CheckRecordings',
            memory_dot_v1_dot_memory__service__pb2.CheckRecordingsRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.CheckRecordingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AttachmentsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadAttachment = channel.stream_unary(
                '/memory.v1.AttachmentsService/UploadAttachment',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.UploadAttachmentRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.UploadAttachmentResponse.FromString,
                _registered_method=True)
        self.GetAttachment = channel.unary_unary(
                '/memory.v1.AttachmentsService/GetAttachment',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.GetAttachmentRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.AttachmentInfo.FromString,
                _registered_method=True)
        self.DownloadAttachment = channel.unary_stream(
                '/memory.v1.AttachmentsService/DownloadAttachment',
                request_serializer=memory_dot_v1_dot_memory__service__pb2.DownloadAttachmentRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__service__pb2.DownloadAttachmentResponse.FromString,
                _registered_method=True)


class AttachmentsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadAttachment(self, request_iterator, context):
        """Upload a file as a stream of chunks. First message must contain metadata.
        Subsequent messages contain file data chunks.
        Server responds once the upload is complete or an error occurs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttachment(self, request, context):
        """Retrieve attachment metadata (not the file content).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadAttachment(self, request, context):
        """Download a file as a stream of chunks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttachmentsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadAttachment': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadAttachment,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.UploadAttachmentRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.UploadAttachmentResponse.SerializeToString,
            ),
            'GetAttachment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttachment,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.GetAttachmentRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.AttachmentInfo.SerializeToString,
            ),
            'DownloadAttachment': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadAttachment,
                    request_deserializer=memory_dot_v1_dot_memory__service__pb2.DownloadAttachmentRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__service__pb2.DownloadAttachmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.v1.AttachmentsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.v1.AttachmentsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttachmentsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadAttachment(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/memory.v1.AttachmentsService/UploadAttachment',
            memory_dot_v1_dot_memory__service__pb2.UploadAttachmentRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.UploadAttachmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttachment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.AttachmentsService/GetAttachment',
            memory_dot_v1_dot_memory__service__pb2.GetAttachmentRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.AttachmentInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadAttachment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/memory.v1.AttachmentsService/DownloadAttachment',
            memory_dot_v1_dot_memory__service__pb2.DownloadAttachmentRequest.SerializeToString,
            memory_dot_v1_dot_memory__service__pb2.DownloadAttachmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
